### ISSUE TITLE
[regression] transformations aren't applied in collection -> single field

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#1241]
When you have mapping like Collection -> single filed transformations aren't applied. It's processed with no exceptions as repeating mapping instead.
mapping.json:
```
} ],
    "mappings" : {
      "mapping" : [ {
        "jsonType" : "io.atlasmap.v2.Mapping",
        "inputField" : [ {
          "jsonType" : "io.atlasmap.json.v2.JsonField",
          "actions" : [ {
            "@type" : "Add"
          } ],
          "docId" : "sourceArrays",
          "index" : 0,
          "path" : "/jsonIntegers<>",
          "fieldType" : "INTEGER",
          "name" : "jsonIntegers",
          "userCreated" : false
        } ],
        "outputField" : [ {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "path" : "/targetFloat",
          "fieldType" : "FLOAT",
          "name" : "targetFloat"
        } ],
        "id" : "mapping.64078"
      } ]
    },
    "lookupTables" : {
      "lookupTable" : [ ]
    },
    "constants" : {
      "constant" : [ ]
    },
    "properties" : {
      "property" : [ ]
    },
    "name" : "UI.176627"
```

**Comment by mmelko** [comment]
Still present

**Comment by jsafarik** [comment]
`TRIED USING SYNDESIS`
Just tried this using odata service, I've done simple integration OData (read) -> Data Mapper -> SQL (insert), and tried to `Add` all the `ID`s of entities returned from the OData service. This is what happened:
![image](https://user-images.githubusercontent.com/46523434/66330689-2f6f3f80-e931-11e9-8b5c-3706c140745e.png)

```
io.atlasmap.api.AtlasException: Errors: [Failed to apply field action: Error processing action Add - The source collection/arry/map must only contain numbers: docId='null', path='null'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:262)
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$TrackDoneEventProcessor.process(ActivityTrackingInterceptStrategy.java:121)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
	at org.apache.camel.util.component.ApiConsumerHelper.processResult(ApiConsumerHelper.java:140)
	at org.apache.camel.util.component.ApiConsumerHelper.getResultsProcessed(ApiConsumerHelper.java:127)
	at org.apache.camel.component.olingo4.Olingo4Consumer.poll(Olingo4Consumer.java:107)
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174)
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by igarashitm** [comment]
OK, I could reproduce it in Syndesis. Now UI generates a bit different mapping for this kind of mapping. Even if source field is only one collection field, it's wrapped with `FieldGroup`, and it's not handled correctly. Although the mapping in the description works, it's still an issue with what UI generates. I'll fix that.
