### ISSUE TITLE
yarn build fails with ENOENT

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#144]
It looks like the parameter substitution for `<%= dasherizedModuleName %>` is not going well. It passes with CircleCI which is using same yarn v1.3.2. @deeleman do you know how to avoid this?
```
$ yarn build
yarn run v1.3.2
$ rimraf ./dist
$ ng-packagr -p package.json
Building Angular library
Generating bundle for @atlasmap/atlasmap.data.mapper
Cleaning bundle build directory
Processing assets
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/tomo/workspace/iPaaS/atlasmap/atlasmap/ui/lib/node_modules/angular-cli/blueprints/component/files/__path__/<%= dasherizedModuleName %>.component.html'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at getFileData (/home/tomo/workspace/iPaaS/atlasmap/atlasmap/ui/node_modules/gulp-inline-ng2-template/parser.js:284:17)
    at /home/tomo/workspace/iPaaS/atlasmap/atlasmap/ui/node_modules/gulp-inline-ng2-template/parser.js:248:22
    at /home/tomo/workspace/iPaaS/atlasmap/atlasmap/ui/node_modules/async/dist/async.js:3866:24
    at replenish (/home/tomo/workspace/iPaaS/atlasmap/atlasmap/ui/node_modules/async/dist/async.js:998:17)
    at /home/tomo/workspace/iPaaS/atlasmap/atlasmap/ui/node_modules/async/dist/async.js:1002:9
    at eachOfLimit (/home/tomo/workspace/iPaaS/atlasmap/atlasmap/ui/node_modules/async/dist/async.js:1027:24)
    at /home/tomo/workspace/iPaaS/atlasmap/atlasmap/ui/node_modules/async/dist/async.js:1032:16
    at _parallel (/home/tomo/workspace/iPaaS/atlasmap/atlasmap/ui/node_modules/async/dist/async.js:3865:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by igarashitm** [comment]
Solved by removing my lib/node_modules - no idea why it was there, why causing problem... nasty system.
