### ISSUE TITLE
Couldn't run .adm mapping file using atlasmap runtime

### ISSUE THREAD

**Issue by ranjith-murugasamy** [atlasmap/atlasmap#2022]
Exception in thread "main" io.atlasmap.api.AtlasValidationException: Invalid UTF-8 start byte 0xbd
 at [Source: (File); line: 1, column: 13]
        at io.atlasmap.core.AtlasMappingService.loadMapping(AtlasMappingService.java:62)
        at io.atlasmap.core.AtlasMappingService.loadMapping(AtlasMappingService.java:85)
        at io.atlasmap.core.DefaultAtlasContext.init(DefaultAtlasContext.java:119)
        at io.atlasmap.core.DefaultAtlasContext.createSession(DefaultAtlasContext.java:905)
        at com.mapper.atlas.AtlasApplication.main(AtlasApplication.java:26)
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 start byte 0xbd
 at [Source: (File); line: 1, column: 13]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidInitial(UTF8StreamJsonParser.java:3570)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._decodeCharForError(UTF8StreamJsonParser.java:3313)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3545)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2652)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:857)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:754)

**Comment by igarashitm** [comment]
You can use ADMArchiveHandler to load .adm file.
Also please use https://groups.google.com/forum/#!forum/atlasmap or Gitter to ask a question.

**Comment by ranjith-murugasamy** [comment]
Thanks a lot @igarashitm for the quick response. Sure i will get in touch with the forum
