### ISSUE TITLE
NullPointer in JavaValidationService when run with Java 10 and above

### ISSUE THREAD

**Issue by christophd** [atlasmap/atlasmap#2260]
The JavaValidationService raises NullPointerException when Atlasmap is run with Java versions newer than version 9. This is because the map of known Java versions stops at Java 9 (see https://github.com/atlasmap/atlasmap/blob/master/lib/modules/java/module/src/main/java/io/atlasmap/java/module/JavaValidationService.java#L74). 

When run with Java 10 and above the validation service runs into this NPE:

```
08:44:21.063 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: java.lang.NullPointerException
08:44:21.063 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at io.atlasmap.java.module.JavaValidationService.validateClass(JavaValidationService.java:132)
08:44:21.063 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at io.atlasmap.java.module.JavaValidationService.validateModuleField(JavaValidationService.java:124)
08:44:21.064 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at io.atlasmap.java.module.JavaValidationService.validateModuleField(JavaValidationService.java:41)
08:44:21.064 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at io.atlasmap.core.validate.BaseModuleValidationService.validateField(BaseModuleValidationService.java:257)
08:44:21.064 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at io.atlasmap.core.validate.BaseModuleValidationService.validateMapMapping(BaseModuleValidationService.java:173)
08:44:21.064 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at io.atlasmap.core.validate.BaseModuleValidationService.validateMappingEntries(BaseModuleValidationService.java:138)
08:44:21.064 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at io.atlasmap.core.validate.BaseModuleValidationService.validateMapping(BaseModuleValidationService.java:104)
08:44:21.064 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at io.atlasmap.java.module.JavaModule.processPreValidation(JavaModule.java:81)
08:44:21.064 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at io.atlasmap.core.DefaultAtlasContext.processValidation(DefaultAtlasContext.java:898)
08:44:21.065 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at io.atlasmap.core.DefaultAtlasContext.process(DefaultAtlasContext.java:456)
08:44:21.065 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:221)
08:44:21.065 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.support.ProcessorEndpoint$1.process(ProcessorEndpoint.java:63)
08:44:21.065 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:67)
08:44:21.065 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:168)
08:44:21.065 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.support.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:93)
08:44:21.065 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:702)
08:44:21.066 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:616)
08:44:21.066 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:148)
08:44:21.066 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:60)
08:44:21.066 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.processor.Pipeline.process(Pipeline.java:147)
08:44:21.066 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
08:44:21.067 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:40)
08:44:21.067 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.http.common.CamelServlet.doService(CamelServlet.java:214)
08:44:21.067 [ream-1469293879] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.http.common.CamelServlet.service(CamelServlet.java:80)
```

**Comment by igarashitm** [comment]
Thanks for the report - I don't think this check makes much sense as we haven't really chased class file compatibility, so I'd vote for removing this.
