### ISSUE TITLE
Test failure on freshly checked out repo

### ISSUE THREAD

**Issue by rhuss** [atlasmap/atlasmap#23]
Doing a `mvn install` on freshly cloned atlasmap repo yields:

```
Results :

Tests in error:
  DateConverterTest.convertFromLong:272 » IllegalArgument java.lang.ArithmeticEx...

Tests run: 343, Failures: 0, Errors: 1, Skipped: 1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Atlas :: Project Build ............................. SUCCESS [  0.159 s]
[INFO] Atlas :: Parent POM ................................ SUCCESS [  0.471 s]
[INFO] Atlas :: Model ..................................... SUCCESS [  9.165 s]
[INFO] Atlas :: API ....................................... SUCCESS [  0.795 s]
[INFO] Atlas :: Core ...................................... FAILURE [  3.820 s]
[INFO] Atlas :: Mock Parent POM ........................... SKIPPED
[INFO] Atlas :: Mock Model ................................ SKIPPED
[INFO] Atlas :: Mock Module ............................... SKIPPED
[INFO] Atlas :: Java Parent POM ........................... SKIPPED
...
```

with the following test result

```
-------------------------------------------------------------------------------
Test set: io.atlasmap.converters.DateConverterTest
-------------------------------------------------------------------------------
Tests run: 32, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.139 sec <<< FAILURE! - in io.atlasmap.converters.DateConverterTest
convertFromLong(io.atlasmap.converters.DateConverterTest)  Time elapsed: 0.007 sec  <<< ERROR!
java.lang.IllegalArgumentException: java.lang.ArithmeticException: long overflow
        at io.atlasmap.converters.DateConverterTest.convertFromLong(DateConverterTest.java:272)
Caused by: java.lang.ArithmeticException: long overflow
        at io.atlasmap.converters.DateConverterTest.convertFromLong(DateConverterTest.java:272)
```

**Comment by mattrpav** [comment]
I'm looking into this. I'm showing works-for-me locally with a fresh checkout and a wipe of ~/.m2/repository/io/atlasmap

**Comment by mattrpav** [comment]
Looks like a JDK 8 bug: [JDK-8074032] (https://bugs.openjdk.java.net/browse/JDK-8074032?jql=text%20~%20%22ofepochmillis%22)

Please try a JDK u90 or higher.

**Comment by rhuss** [comment]
Works for me now with _131. Maybe you can document this requirement somewhere? 

Otherwise, I'm fine with the resolution.

**Comment by mattrpav** [comment]
Good idea. I'll document > u90 and recommend u131 (container users will want 131 for sure)
