### ISSUE TITLE
Converter not found for sourceType: INTEGER targetType: NUMBER during Number-related transformation

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#233]
I have created simple mapping from Integer to Integer via UI and following exception is thrown during actual camel processing: 
```
Caused by: io.atlasmap.api.AtlasException: Errors: [Unable to auto-convert for sourceType=INTEGER targetType=INTEGER targetPath=/targetInteger msg=Converter not found for sourceType: INTEGER targetType: NUMBER: docId='io.atlasmap.qe.test.TargetMappingTestClass', path='/targetInteger'],
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:187)
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
```
Mapping works fine without defined field action.
Created mappings.xml:

```xml
<Mappings>
        <Mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Mapping" id="mapping.990772" mappingType="Map">
            <InputField xsi:type="ns2:JavaField" name="sourceInteger" docId="io.atlasmap.qe.test.SourceMappingTestClass" path="/sourceInteger" fieldType="Integer"/>
            <OutputField xsi:type="ns2:JavaField" name="targetInteger" docId="io.atlasmap.qe.test.TargetMappingTestClass" path="/targetInteger" fieldType="Integer">
                <Actions>
                    <AbsoluteValue/>
                </Actions>
            </OutputField>
        </Mapping>
    </Mappings>
```

**Comment by igarashitm** [comment]
This is a bug on picking up a TypeConverter, it should know INTEGER is already a kind of NUMBER and just return.
