### ISSUE TITLE
Fix E2ETest

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2351]
Intermittently it fails in CircleCI builds, potentially some other file than exported adm is detected and exit the loop.

**Comment by igarashitm** [comment]
It still fails sometime... seems it misses file create event between poll timeout and next poll.

**Comment by igarashitm** [comment]
Again, the exception needs to be caught was wrong
```
java.nio.file.ClosedWatchServiceException
	at sun.nio.fs.AbstractWatchService.checkOpen(AbstractWatchService.java:80)
	at sun.nio.fs.AbstractWatchService.checkKey(AbstractWatchService.java:92)
	at sun.nio.fs.AbstractWatchService.take(AbstractWatchService.java:119)
	at io.atlasmap.standalone.E2ETest.test(E2ETest.java:156)
```

**Comment by igarashitm** [comment]
Actually the real problem is that why it reached to timeout... .crdownload file is created, but the final .adm file is not. Is the rename in the same directory not notified as a ENTRY_CREATE event?
