### ISSUE TITLE
JSON to JSON adm based mapping is not working - io.atlasmap.api.AtlasException

### ISSUE THREAD

**Issue by sanjay-90210** [atlasmap/atlasmap#2449]
[pump-device .zip](https://github.com/atlasmap/atlasmap/files/5458407/pump-device.zip)

[pump.txt](https://github.com/atlasmap/atlasmap/files/5458412/pump.txt)

Version: 2.1.0
Java : 
openjdk version "1.8.0_232"
OpenJDK Runtime Environment Corretto-8.232.09.1 (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM Corretto-8.232.09.1 (build 25.232-b09, mixed mode)

Json to Json mapping using adm file is failing with the following exception:

Exception in thread "main" io.atlasmap.api.AtlasException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "id" (class io.atlasmap.v2.DataSourceMetadata), not marked as ignorable (8 known properties: "documentType", "documentId", "name", "inspectionType", "dataSourceType", "isSource", "source", "inspectionParameters"])
 at [Source: (GZIPInputStream); line: 11, column: 18] (through reference chain: io.atlasmap.v2.ADMDigest["exportMeta"]->java.lang.Object[][0]->io.atlasmap.v2.DataSourceMetadata["id"])
	at io.atlasmap.core.ADMArchiveHandler.getDataSourceMetadataMap(ADMArchiveHandler.java:327)
	at io.atlasmap.core.DefaultAtlasContext.init(DefaultAtlasContext.java:139)
	at io.atlasmap.core.DefaultAtlasContext.createSession(DefaultAtlasContext.java:991)
	at com.kalkitech.test.atlasmap.Main.main(Main.java:19)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "id" (class io.atlasmap.v2.DataSourceMetadata), not marked as ignorable (8 known properties: "documentType", "documentId", "name", "inspectionType", "dataSourceType", "isSource", "source", "inspectionParameters"])
 at [Source: (GZIPInputStream); line: 11, column: 18] (through reference chain: io.atlasmap.v2.ADMDigest["exportMeta"]->java.lang.Object[][0]->io.atlasmap.v2.DataSourceMetadata["id"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1212)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1604)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1582)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:299)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3503)
	at io.atlasmap.core.ADMArchiveHandler.getDataSourceMetadataMap(ADMArchiveHandler.java:315)

Once i add the id annotation [@JsonProperty("id")] as given below, things work fine :
import com.fasterxml.jackson.annotation.JsonProperty;

public class DataSourceMetadata implements Serializable {

    private static final long serialVersionUID = 1L;

    @JsonProperty("id")
    private String documentId;
    private String name;
    private String documentType;
    private InspectionType inspectionType;
    @JsonProperty("isSource")
    private boolean isSource;

**Comment by igarashitm** [comment]
Thanks for catching, I'll align it to `id` as a primary name.
