### ISSUE TITLE
FHIR doc causes runtime OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2564]
Don't know if this is something new.  My laptop worked with this file before.

1.  Import .../atlasmap/ui/test-resources/adm/mockdocfhir.adm

Server error: `Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded`
Full dump:

<pre><font color="#1E8C32">2021-02-09 13:56:58.818 </font><font color="#6AC911">DEBUG</font> <font color="#75507B">12558</font> --- [  XNIO-1 task-2] <font color="#06989A">i.a.core.DefaultAtlasModuleInfoRegistry </font> : Registered AtlasModule &apos;CsvModule&apos; with JMX
<font color="#1E8C32">2021-02-09 13:56:58.818 </font><font color="#6AC911">DEBUG</font> <font color="#75507B">12558</font> --- [  XNIO-1 task-2] <font color="#06989A">i.a.core.DefaultAtlasContextFactory     </font> : Loaded: 5 of 5 detected modules
<font color="#1E8C32">2021-02-09 13:56:58.901 </font><font color="#6AC911">DEBUG</font> <font color="#75507B">12558</font> --- [  XNIO-1 task-2] <font color="#06989A">io.atlasmap.service.AtlasService        </font> : Ping...  responding with &apos;pong&apos;.
<font color="#1E8C32">2021-02-09 13:56:58.908 </font><font color="#6AC911">DEBUG</font> <font color="#75507B">12558</font> --- [  XNIO-1 task-2] <font color="#06989A">io.atlasmap.service.AtlasService        </font> : getMappingRequest: GZ &apos;0&apos;
<font color="#1E8C32">2021-02-09 13:56:59.113 </font><font color="#6AC911">DEBUG</font> <font color="#75507B">12558</font> --- [  XNIO-1 task-2] <font color="#06989A">io.atlasmap.service.AtlasLibraryLoader  </font> : Loading Class:io.atlasmap.xml.v2.XmlInspectionRequest
<font color="#1E8C32">2021-02-09 13:57:20.982 </font><font color="#CC0000">ERROR</font> <font color="#75507B">12558</font> --- [  XNIO-1 task-2] <font color="#06989A">io.undertow.request                     </font> : UT005023: Exception handling request to /v2/atlas/xml/inspect

org.jboss.resteasy.spi.UnhandledException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106) ~[resteasy-core-4.5.8.Final.jar:4.5.8.Final]
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372) ~[resteasy-core-4.5.8.Final.jar:4.5.8.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218) ~[resteasy-core-4.5.8.Final.jar:4.5.8.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519) ~[resteasy-core-4.5.8.Final.jar:4.5.8.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261) ~[resteasy-core-4.5.8.Final.jar:4.5.8.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161) ~[resteasy-core-4.5.8.Final.jar:4.5.8.Final]
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364) ~[resteasy-core-4.5.8.Final.jar:4.5.8.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164) ~[resteasy-core-4.5.8.Final.jar:4.5.8.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247) ~[resteasy-core-4.5.8.Final.jar:4.5.8.Final]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249) ~[resteasy-core-4.5.8.Final.jar:4.5.8.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60) ~[resteasy-core-4.5.8.Final.jar:4.5.8.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55) ~[resteasy-core-4.5.8.Final.jar:4.5.8.Final]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar:4.0.4]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:130) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) ~[spring-security-web-5.4.2.jar:5.4.2]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) ~[spring-web-5.3.3.jar:5.3.3]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) ~[spring-boot-actuator-2.4.2.jar:2.4.2]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) ~[undertow-core-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) ~[undertow-core-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) ~[undertow-core-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) ~[undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269) [undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78) [undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133) [undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130) [undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249) [undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78) [undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99) [undertow-servlet-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) [undertow-core-2.2.3.Final.jar:2.2.3.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841) [undertow-core-2.2.3.Final.jar:2.2.3.Final]
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) [jboss-threads-3.1.0.Final.jar:3.1.0.Final]
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) [jboss-threads-3.1.0.Final.jar:3.1.0.Final]
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) [jboss-threads-3.1.0.Final.jar:3.1.0.Final]
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) [jboss-threads-3.1.0.Final.jar:3.1.0.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_232]
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.HashMap.newNode(HashMap.java:1750) ~[na:1.8.0_232]
	at java.util.HashMap.putVal(HashMap.java:631) ~[na:1.8.0_232]
	at java.util.HashMap.put(HashMap.java:612) ~[na:1.8.0_232]
	at java.util.HashSet.add(HashSet.java:220) ~[na:1.8.0_232]
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344) ~[na:1.8.0_232]
	at java.util.HashSet.&lt;init&gt;(HashSet.java:120) ~[na:1.8.0_232]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printGroup(XmlSchemaInspector.java:249) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printGroupDecl(XmlSchemaInspector.java:256) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printParticle(XmlSchemaInspector.java:235) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printGroup(XmlSchemaInspector.java:250) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printGroupDecl(XmlSchemaInspector.java:256) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printParticle(XmlSchemaInspector.java:235) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printGroup(XmlSchemaInspector.java:250) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printParticle(XmlSchemaInspector.java:233) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printComplexType(XmlSchemaInspector.java:224) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printElement(XmlSchemaInspector.java:284) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printParticle(XmlSchemaInspector.java:238) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printGroup(XmlSchemaInspector.java:250) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printGroupDecl(XmlSchemaInspector.java:256) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printParticle(XmlSchemaInspector.java:235) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printGroup(XmlSchemaInspector.java:250) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printGroupDecl(XmlSchemaInspector.java:256) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printParticle(XmlSchemaInspector.java:235) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printGroup(XmlSchemaInspector.java:250) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printParticle(XmlSchemaInspector.java:233) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printComplexType(XmlSchemaInspector.java:224) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printElement(XmlSchemaInspector.java:284) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printParticle(XmlSchemaInspector.java:238) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printGroup(XmlSchemaInspector.java:250) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printGroupDecl(XmlSchemaInspector.java:256) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printParticle(XmlSchemaInspector.java:235) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.xml.inspect.XmlSchemaInspector.printGroup(XmlSchemaInspector.java:250) ~[atlas-xml-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
</pre>

**Comment by igarashitm** [comment]
I think this mockdoc is using old schema which includes deadly recursive XHTML tags, need to be re-created with https://github.com/atlasmap/atlasmap/blame/master/lib/modules/xml/core/src/test/resources/inspect/fhir-patient.xsd

**Comment by igarashitm** [comment]
Actually FHIR inspection runs as a part of build with this one
https://github.com/atlasmap/atlasmap/blob/master/ui/test-resources/xml/schema/fhir-patient.xsd
