### ISSUE TITLE
Unable to convert various date types (Date -> ZonedDateTime,java.sql.Date etc.)

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#263]
I was trying to map `Date` type to `ZonedDateTime` but it seems that runtime is looking for `zonedDT` field setter with` java.util.Date` type instead of `java.time.ZonedDateTime `.  I believe it's because both are interpreted as DateTimeTZ type. The same is happening with `java.sql.Date`

 Following exception was thrown:
 ```
Caused by: io.atlasmap.api.AtlasException: Unable to set value for path: /zonedDT parentObject: io.atlasmap.qe.test.TargetMappingTestClass childObject: java.util.Date
	at io.atlasmap.java.core.JavaWriterUtil.setObjectOnParent(JavaWriterUtil.java:195)
	at io.atlasmap.java.core.DocumentJavaFieldWriter.addChildObject(DocumentJavaFieldWriter.java:523)
	at io.atlasmap.java.core.DocumentJavaFieldWriter.write(DocumentJavaFieldWriter.java:117)
	at io.atlasmap.java.module.JavaModule.processTargetFieldMapping(JavaModule.java:178)
	at io.atlasmap.core.DefaultAtlasContext.processTargetFieldMappings(DefaultAtlasContext.java:420)
	at io.atlasmap.core.DefaultAtlasContext.process(DefaultAtlasContext.java:272)
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:191)
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
```

Generated mapping.xml:
```xml
 <Mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Mapping" id="mapping.92625" mappingType="Map">
            <InputField xsi:type="ns2:JavaField" name="sourceDate" docId="io.atlasmap.qe.test.SourceMappingTestClass" path="/sourceDate" fieldType="DateTimeTZ"/>
            <OutputField xsi:type="ns2:JavaField" name="zonedDT" docId="io.atlasmap.qe.test.TargetMappingTestClass" path="/zonedDT" fieldType="DateTimeTZ"/>
```

**Comment by igarashitm** [comment]
#322 added basic support for those, but not yet for java.sql.*. Let's see if we have usecases for those.

AtlasMap official representatives as of today:
|FieldType|Class|
|DATE|java.time.LocalDate|
|TIME|java.time.LocalTime|
|DATE_TIME|java.util.Date|
|DATE_TZ|java.time.ZonedDateTime|
|TIME_TZ|java.time.ZonedDateTime|
|DATE_TIME_TZ|java.time.ZonedDateTime|

**Comment by igarashitm** [comment]
BTW as java.sql.{Time,Date,Timestamp} are all subclasses of java.util.Date, I expect it to fallback to DateConverter once #320 is addressed.

**Comment by mmelko** [comment]
I'm still hitting this: 
`
Caused by: java.lang.NoSuchMethodException: Unable to resolve expected setter 'setLocalDateTime' for path: /dateObjectVariable/localDateTime, on object: io.atlasmap.qe.test.DatesObject@88dddacd
	at io.atlasmap.java.core.JavaWriterUtil.resolveSetMethod(JavaWriterUtil.java:255)
	at io.atlasmap.java.core.JavaWriterUtil.setObjectOnParent(JavaWriterUtil.java:166)
	... 72 common frames omitted
14:09:58.098 [main] DEBUG org.apache.camel.processor.Pipeline - Message exchange has failed: so breaking out of pipeline for exchange: Exchange[ID-ovpn-204-124-brq-redhat-com-1520255396957-0-1] Exception: io.atlasmap.api.AtlasException: Unable to set value for path: /dateObjectVariable/localDateTime parentObject: io.atlasmap.qe.test.DatesObject childObject: java.util.Date
`

**Comment by igarashitm** [comment]
Hi @mmelko , can you file a separate issue with exact combination of field types? As #320 fix also affects the result of Java inspection, might be required to re-create the mapping from UI.

**Comment by mmelko** [comment]
I've just updated my comment.  I'm always creating mappings fro UI. And sure I will ;)

**Comment by igarashitm** [comment]
OK, so the problem is that the target field is expecting `java.time.LocalDateTime` which is not an official representative of `FieldType.DATE_TIME`, `java.util.Date`. It still should be supported. I'll take a look.

**Comment by mmelko** [comment]
full mapping.xml: 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<AtlasMapping xmlns="http://atlasmap.io/v2" xmlns:ns2="http://atlasmap.io/java/v2" xmlns:ns3="http://atlasmap.io/xml/v2" xmlns:ns4="http://atlasmap.io/json/v2" name="UI.439250">
    <DataSource id="io.atlasmap.qe.test.SourceMappingTestClass" uri="atlas:java:io.atlasmap.qe.test.SourceMappingTestClass?className=io.atlasmap.qe.test.SourceMappingTestClass" dataSourceType="Source"/>
    <DataSource id="io.atlasmap.qe.test.SourceListsClass" uri="atlas:java:io.atlasmap.qe.test.SourceListsClass?className=io.atlasmap.qe.test.SourceListsClass" dataSourceType="Source"/>
    <DataSource id="io.atlasmap.qe.test.SmallMappingTestClass" uri="atlas:java:io.atlasmap.qe.test.SmallMappingTestClass?className=io.atlasmap.qe.test.SmallMappingTestClass" dataSourceType="Source"/>
    <DataSource id="io.atlasmap.qe.test.TargetMappingTestClass" uri="atlas:java:io.atlasmap.qe.test.TargetMappingTestClass?className=io.atlasmap.qe.test.TargetMappingTestClass" dataSourceType="Target"/>
    <DataSource id="io.atlasmap.qe.test.StringObject" uri="atlas:java:io.atlasmap.qe.test.StringObject?className=io.atlasmap.qe.test.StringObject" dataSourceType="Target"/>
    <DataSource id="io.atlasmap.qe.test.TargetListsClass" uri="atlas:java:io.atlasmap.qe.test.TargetListsClass?className=io.atlasmap.qe.test.TargetListsClass" dataSourceType="Target"/>
    <Mappings>
        <Mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Mapping" id="mapping.333168" mappingType="Map">
            <InputField xsi:type="ns2:JavaField" name="sourceDate" docId="io.atlasmap.qe.test.SourceMappingTestClass" path="/sourceDate" fieldType="DateTime"/>
            <OutputField xsi:type="ns2:JavaField" name="standardJavaDate" docId="io.atlasmap.qe.test.TargetMappingTestClass" path="/dateObjectVariable/standardJavaDate" fieldType="DateTime"/>
        </Mapping>
        <Mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Mapping" id="mapping.99964" mappingType="Map">
            <InputField xsi:type="ns2:JavaField" name="sourceDate" docId="io.atlasmap.qe.test.SourceMappingTestClass" path="/sourceDate" fieldType="DateTime"/>
            <OutputField xsi:type="ns2:JavaField" name="time" docId="io.atlasmap.qe.test.TargetMappingTestClass" path="/dateObjectVariable/time" fieldType="DateTime"/>
        </Mapping>
        <Mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Mapping" id="mapping.886573" mappingType="Map">
            <InputField xsi:type="ns2:JavaField" name="sourceDate" docId="io.atlasmap.qe.test.SourceMappingTestClass" path="/sourceDate" fieldType="DateTime"/>
            <OutputField xsi:type="ns2:JavaField" name="zonedDateTime" docId="io.atlasmap.qe.test.TargetMappingTestClass" path="/dateObjectVariable/zonedDateTime" fieldType="DateTimeTZ"/>
        </Mapping>
    </Mappings>
    <LookupTables/>
    <Properties/>
</AtlasMapping>
```
