### ISSUE TITLE
Failed to convert field value '-0.96' into type 'DOUBLE'

### ISSUE THREAD

**Issue by Duvel** [atlasmap/atlasmap#2647]
I'm trying to map data from the OpenWeather API en created a mapping in the standalone application. Now when I try to process data retrieved from the API in Quarkus/Apache Camel, I get the mentioned error. The values are the negative values for the temperature in Celsius around here.

I'm using Quarkus 1.8.0 with Camel 3.9.0 which results in Atlasmap 2.1.6.

**Comment by Duvel** [comment]
`2021-04-04 11:43:16,099 WARN  [org.apa.cam.com.tim.TimerConsumer] (Camel (camel-1) thread #0 - timer://test) Error processing exchange. Exchange[96BC83BD3309264-0000000000000001]. Caused by: [io.atlasmap.api.AtlasException - Errors: [Failed to convert field value '-0.96' into type 'DOUBLE': Document='weather(ID:weather-16e3d3ba-3fb6-4dde-8365-048e648e8492)', path='/daily<2>/temp/min'], [Failed to convert field value '-1.68' into type 'DOUBLE': Document='weather(ID:weather-16e3d3ba-3fb6-4dde-8365-048e648e8492)', path='/daily<3>/temp/min'], [Failed to convert field value '-0.37' into type 'DOUBLE': Document='weather(ID:weather-16e3d3ba-3fb6-4dde-8365-048e648e8492)', path='/daily<4>/temp/min'], [Failed to convert field value '-0.54' into type 'DOUBLE': Document='weather(ID:weather-16e3d3ba-3fb6-4dde-8365-048e648e8492)', path='/daily<7>/temp/min'], ]: io.atlasmap.api.AtlasException: Errors: [Failed to convert field value '-0.96' into type 'DOUBLE': Document='weather(ID:weather-16e3d3ba-3fb6-4dde-8365-048e648e8492)', path='/daily<2>/temp/min'], [Failed to convert field value '-1.68' into type 'DOUBLE': Document='weather(ID:weather-16e3d3ba-3fb6-4dde-8365-048e648e8492)', path='/daily<3>/temp/min'], [Failed to convert field value '-0.37' into type 'DOUBLE': Document='weather(ID:weather-16e3d3ba-3fb6-4dde-8365-048e648e8492)', path='/daily<4>/temp/min'], [Failed to convert field value '-0.54' into type 'DOUBLE': Document='weather(ID:weather-16e3d3ba-3fb6-4dde-8365-048e648e8492)', path='/daily<7>/temp/min'], 
	at org.apache.camel.component.atlasmap.AtlasMapEndpoint.onExchange(AtlasMapEndpoint.java:222)
	at org.apache.camel.support.ProcessorEndpoint$1.process(ProcessorEndpoint.java:61)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:172)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:439)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:62)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:167)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:388)
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:209)
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:76)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)`

**Comment by Duvel** [comment]
In the standalone application a negative value is also not allowed in the preview:

```
ERROR[/daily<>/temp/max]: Wrong format for source value : Invoking type convertor failed - String -1 is greater than Double.MAX_VALUE or less than Double.MIN_VALUE
```

**Comment by igarashitm** [comment]
Thanks for reporting, a bug found in handling double MIN/MAX.
