### ISSUE TITLE
Null value in target during repeating mappings

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#273]
Exception is thrown for every collection member (listOfString<1,2..etc>: 
` ` ` ERROR io.atlasmap.java.core.DocumentJavaFieldReader - listOfStrings<0>
java.lang.NoSuchFieldException: listOfStrings<0>
	at java.lang.Class.getField(Class.java:1703)
	at io.atlasmap.java.core.DocumentJavaFieldReader.getValueFromMemberField(DocumentJavaFieldReader.java:129)
	at io.atlasmap.java.core.DocumentJavaFieldReader.populateSourceFieldValue(DocumentJavaFieldReader.java:76)
	at io.atlasmap.java.core.DocumentJavaFieldReader.read(DocumentJavaFieldReader.java:49)
	at io.atlasmap.java.module.JavaModule.processSourceFieldMapping(JavaModule.java:163)
	at io.atlasmap.core.DefaultAtlasContext.processSourceFieldMappings(DefaultAtlasContext.java:399)
	at io.atlasmap.core.DefaultAtlasContext.process(DefaultAtlasContext.java:269)
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:191)
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.component.direct.DirectBlockingProducer.process(DirectBlockingProducer.java:53)
	at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:186)
	at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:86)
	at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:541)
	at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:506)
	at org.apache.camel.impl.ProducerCache.doInProducer(ProducerCache.java:369)
	at org.apache.camel.impl.ProducerCache.sendExchange(ProducerCache.java:506)
	at org.apache.camel.impl.ProducerCache.send(ProducerCache.java:229)
	at org.apache.camel.impl.DefaultProducerTemplate.send(DefaultProducerTemplate.java:144)
	at org.apache.camel.impl.DefaultProducerTemplate.sendBodyAndProperty(DefaultProducerTemplate.java:223)
	at org.apache.camel.impl.DefaultProducerTemplate.sendBodyAndProperty(DefaultProducerTemplate.java:218)
	at io.atlasmap.qe.test.MappingValidator.processMapping(MappingValidator.java:73)
	at io.atlasmap.qe.test.MappingValidator.verifyMultiObjectMapping(MappingValidator.java:103)
	at io.atlasmap.qe.test.MappingValidator.verifyMultiObjectMapping(MappingValidator.java:99)
`` ` 
generated mapping:
```xml
<Mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Collection" collectionType="List" mappingType="Collection">
            <Mappings>
                <Mapping xsi:type="Mapping" id="mapping.582428" mappingType="Map">
                    <InputField xsi:type="ns2:JavaField" name="listOfStrings" docId="io.atlasmap.qe.test.SmallMappingTestClass" path="/listOfStrings&lt;&gt;" fieldType="String"/>
                    <OutputField xsi:type="ns2:JavaField" name="targetString" docId="io.atlasmap.qe.test.TargetMappingTestClass" path="/targetString" fieldType="String">
                        <Actions>
                            <Concatenate delimiter="-"/>
                        </Actions>
                    </OutputField>
                </Mapping>
            </Mappings>
        </Mapping>
```

**Comment by mmelko** [comment]
I verified with List of complex values and it does work properly. So NPE happens only when collection of primitive types is involved.

**Comment by igarashitm** [comment]
Due to #210 this Collection->non-Collection mapping should not be allowed. I thought there is a validation error for that, but now I can't see it. It might have been unexpectedly disabled somehow...
