### ISSUE TITLE
UI: New React warning on Mapping Details add-to-mapping pulldown menu

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2887]
Just noticed this today.  
1.  Establish a simple mapping.
2. Click the add-to-mapping select menu (source or target) in the Mapping Details pane

*This does not occur with the expression select menu.*

2.2.2 is okay

![sc0](https://user-images.githubusercontent.com/2981421/120497806-b71e8300-c38c-11eb-8ea2-c2c72367f2d8.png)

Causes:

`react-dom.development.js:67 Warning: React does not recognize the `isFocused` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isfocused` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at SelectGroup (http://localhost:6006/vendors~main.iframe.bundle.js:7423:11)
    at ul
    at SelectMenuWithRef (http://localhost:6006/vendors~main.iframe.bundle.js:7464:1)
    at http://localhost:6006/vendors~main.iframe.bundle.js:7587:204
    at div
    at GenerateId (http://localhost:6006/vendors~main.iframe.bundle.js:9190:9)
    at Select (http://localhost:6006/vendors~main.iframe.bundle.js:6750:9)
    at div
    at AddFieldTypeahead (http://localhost:6006/main.iframe.bundle.js:22255:21)
    at div
    at MappingFields (http://localhost:6006/main.iframe.bundle.js:32389:20)
    at div
    at div
    at StackItem (http://localhost:6006/vendors~main.iframe.bundle.js:12962:11)
    at div
    at Stack (http://localhost:6006/vendors~main.iframe.bundle.js:12932:11)
    at MappingDetailsSidebar (http://localhost:6006/main.iframe.bundle.js:21376:23)
    at MappingDetailsView (http://localhost:6006/main.iframe.bundle.js:42709:28)
    at div
    at div
    at TopologySideBar (http://localhost:6006/vendors~main.iframe.bundle.js:27693:11)
    at Sidebar (http://localhost:6006/main.iframe.bundle.js:21628:19)
    at div
    at StackItem (http://localhost:6006/vendors~main.iframe.bundle.js:12962:11)
    at div
    at Stack (http://localhost:6006/vendors~main.iframe.bundle.js:12932:11)
    at http://localhost:6006/main.iframe.bundle.js:21141:22
    at CanvasProvider (http://localhost:6006/main.iframe.bundle.js:24176:23)
    at DndProvider (http://localhost:6006/vendors~main.iframe.bundle.js:195478:23)
    at TouchAndPointerProvider (http://localhost:6006/main.iframe.bundle.js:37937:23)
    at FieldsDndProvider (http://localhost:6006/main.iframe.bundle.js:37960:24)
    at Atlasmap (http://localhost:6006/main.iframe.bundle.js:11935:31)
    at AtlasmapProvider (http://localhost:6006/main.iframe.bundle.js:12472:43)
    at div
    at unboundStoryFn (http://localhost:6006/vendors~main.iframe.bundle.js:53813:30)
    at ErrorBoundary (http://localhost:6006/vendors~main.iframe.bundle.js:66081:5)
printWarning @ react-dom.development.js:67
react-dom.development.js:67 Warning: React does not recognize the `inputId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inputid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at SelectGroup (http://localhost:6006/vendors~main.iframe.bundle.js:7423:11)
    at ul
    at SelectMenuWithRef (http://localhost:6006/vendors~main.iframe.bundle.js:7464:1)
    at http://localhost:6006/vendors~main.iframe.bundle.js:7587:204
    at div
    at GenerateId (http://localhost:6006/vendors~main.iframe.bundle.js:9190:9)
    at Select (http://localhost:6006/vendors~main.iframe.bundle.js:6750:9)
    at div
    at AddFieldTypeahead (http://localhost:6006/main.iframe.bundle.js:22255:21)
    at div
    at MappingFields (http://localhost:6006/main.iframe.bundle.js:32389:20)
    at div
    at div
    at StackItem (http://localhost:6006/vendors~main.iframe.bundle.js:12962:11)
    at div
    at Stack (http://localhost:6006/vendors~main.iframe.bundle.js:12932:11)
    at MappingDetailsSidebar (http://localhost:6006/main.iframe.bundle.js:21376:23)
    at MappingDetailsView (http://localhost:6006/main.iframe.bundle.js:42709:28)
    at div
    at div
    at TopologySideBar (http://localhost:6006/vendors~main.iframe.bundle.js:27693:11)
    at Sidebar (http://localhost:6006/main.iframe.bundle.js:21628:19)
    at div
    at StackItem (http://localhost:6006/vendors~main.iframe.bundle.js:12962:11)
    at div
    at Stack (http://localhost:6006/vendors~main.iframe.bundle.js:12932:11)
    at http://localhost:6006/main.iframe.bundle.js:21141:22
    at CanvasProvider (http://localhost:6006/main.iframe.bundle.js:24176:23)
    at DndProvider (http://localhost:6006/vendors~main.iframe.bundle.js:195478:23)
    at TouchAndPointerProvider (http://localhost:6006/main.iframe.bundle.js:37937:23)
    at FieldsDndProvider (http://localhost:6006/main.iframe.bundle.js:37960:24)
    at Atlasmap (http://localhost:6006/main.iframe.bundle.js:11935:31)
    at AtlasmapProvider (http://localhost:6006/main.iframe.bundle.js:12472:43)
    at div
    at unboundStoryFn (http://localhost:6006/vendors~main.iframe.bundle.js:53813:30)
    at ErrorBoundary (http://localhost:6006/vendors~main.iframe.bundle.js:66081:5)
printWarning @ react-dom.development.js:67
react-dom.development.js:67 Warning: React does not recognize the `isSelected` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isselected` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at SelectGroup (http://localhost:6006/vendors~main.iframe.bundle.js:7423:11)
    at ul
    at SelectMenuWithRef (http://localhost:6006/vendors~main.iframe.bundle.js:7464:1)
    at http://localhost:6006/vendors~main.iframe.bundle.js:7587:204
    at div
    at GenerateId (http://localhost:6006/vendors~main.iframe.bundle.js:9190:9)
    at Select (http://localhost:6006/vendors~main.iframe.bundle.js:6750:9)
    at div
    at AddFieldTypeahead (http://localhost:6006/main.iframe.bundle.js:22255:21)
    at div
    at MappingFields (http://localhost:6006/main.iframe.bundle.js:32389:20)
    at div
    at div
    at StackItem (http://localhost:6006/vendors~main.iframe.bundle.js:12962:11)
    at div
    at Stack (http://localhost:6006/vendors~main.iframe.bundle.js:12932:11)
    at MappingDetailsSidebar (http://localhost:6006/main.iframe.bundle.js:21376:23)
    at MappingDetailsView (http://localhost:6006/main.iframe.bundle.js:42709:28)
    at div
    at div
    at TopologySideBar (http://localhost:6006/vendors~main.iframe.bundle.js:27693:11)
    at Sidebar (http://localhost:6006/main.iframe.bundle.js:21628:19)
    at div
    at StackItem (http://localhost:6006/vendors~main.iframe.bundle.js:12962:11)
    at div
    at Stack (http://localhost:6006/vendors~main.iframe.bundle.js:12932:11)
    at http://localhost:6006/main.iframe.bundle.js:21141:22
    at CanvasProvider (http://localhost:6006/main.iframe.bundle.js:24176:23)
    at DndProvider (http://localhost:6006/vendors~main.iframe.bundle.js:195478:23)
    at TouchAndPointerProvider (http://localhost:6006/main.iframe.bundle.js:37937:23)
    at FieldsDndProvider (http://localhost:6006/main.iframe.bundle.js:37960:24)
    at Atlasmap (http://localhost:6006/main.iframe.bundle.js:11935:31)
    at AtlasmapProvider (http://localhost:6006/main.iframe.bundle.js:12472:43)
    at div
    at unboundStoryFn (http://localhost:6006/vendors~main.iframe.bundle.js:53813:30)
    at ErrorBoundary (http://localhost:6006/vendors~main.iframe.bundle.js:66081:5)
printWarning @ react-dom.development.js:67
react-dom.development.js:67 Warning: React does not recognize the `sendRef` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `sendref` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at SelectGroup (http://localhost:6006/vendors~main.iframe.bundle.js:7423:11)
    at ul
    at SelectMenuWithRef (http://localhost:6006/vendors~main.iframe.bundle.js:7464:1)
    at http://localhost:6006/vendors~main.iframe.bundle.js:7587:204
    at div
    at GenerateId (http://localhost:6006/vendors~main.iframe.bundle.js:9190:9)
    at Select (http://localhost:6006/vendors~main.iframe.bundle.js:6750:9)
    at div
    at AddFieldTypeahead (http://localhost:6006/main.iframe.bundle.js:22255:21)
    at div
    at MappingFields (http://localhost:6006/main.iframe.bundle.js:32389:20)
    at div
    at div
    at StackItem (http://localhost:6006/vendors~main.iframe.bundle.js:12962:11)
    at div
    at Stack (http://localhost:6006/vendors~main.iframe.bundle.js:12932:11)
    at MappingDetailsSidebar (http://localhost:6006/main.iframe.bundle.js:21376:23)
    at MappingDetailsView (http://localhost:6006/main.iframe.bundle.js:42709:28)
    at div
    at div
    at TopologySideBar (http://localhost:6006/vendors~main.iframe.bundle.js:27693:11)
    at Sidebar (http://localhost:6006/main.iframe.bundle.js:21628:19)
    at div
    at StackItem (http://localhost:6006/vendors~main.iframe.bundle.js:12962:11)
    at div
    at Stack (http://localhost:6006/vendors~main.iframe.bundle.js:12932:11)
    at http://localhost:6006/main.iframe.bundle.js:21141:22
    at CanvasProvider (http://localhost:6006/main.iframe.bundle.js:24176:23)
    at DndProvider (http://localhost:6006/vendors~main.iframe.bundle.js:195478:23)
    at TouchAndPointerProvider (http://localhost:6006/main.iframe.bundle.js:37937:23)
    at FieldsDndProvider (http://localhost:6006/main.iframe.bundle.js:37960:24)
    at Atlasmap (http://localhost:6006/main.iframe.bundle.js:11935:31)
    at AtlasmapProvider (http://localhost:6006/main.iframe.bundle.js:12472:43)
    at div
    at unboundStoryFn (http://localhost:6006/vendors~main.iframe.bundle.js:53813:30)
    at ErrorBoundary (http://localhost:6006/vendors~main.iframe.bundle.js:66081:5)
printWarning @ react-dom.development.js:67
react-dom.development.js:67 Warning: React does not recognize the `keyHandler` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `keyhandler` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at SelectGroup (http://localhost:6006/vendors~main.iframe.bundle.js:7423:11)
    at ul
    at SelectMenuWithRef (http://localhost:6006/vendors~main.iframe.bundle.js:7464:1)
    at http://localhost:6006/vendors~main.iframe.bundle.js:7587:204
    at div
    at GenerateId (http://localhost:6006/vendors~main.iframe.bundle.js:9190:9)
    at Select (http://localhost:6006/vendors~main.iframe.bundle.js:6750:9)
    at div
    at AddFieldTypeahead (http://localhost:6006/main.iframe.bundle.js:22255:21)
    at div
    at MappingFields (http://localhost:6006/main.iframe.bundle.js:32389:20)
    at div
    at div
    at StackItem (http://localhost:6006/vendors~main.iframe.bundle.js:12962:11)
    at div
    at Stack (http://localhost:6006/vendors~main.iframe.bundle.js:12932:11)
    at MappingDetailsSidebar (http://localhost:6006/main.iframe.bundle.js:21376:23)
    at MappingDetailsView (http://localhost:6006/main.iframe.bundle.js:42709:28)
    at div
    at div
    at TopologySideBar (http://localhost:6006/vendors~main.iframe.bundle.js:27693:11)
    at Sidebar (http://localhost:6006/main.iframe.bundle.js:21628:19)
    at div
    at StackItem (http://localhost:6006/vendors~main.iframe.bundle.js:12962:11)
    at div
    at Stack (http://localhost:6006/vendors~main.iframe.bundle.js:12932:11)
    at http://localhost:6006/main.iframe.bundle.js:21141:22
    at CanvasProvider (http://localhost:6006/main.iframe.bundle.js:24176:23)
    at DndProvider (http://localhost:6006/vendors~main.iframe.bundle.js:195478:23)
    at TouchAndPointerProvider (http://localhost:6006/main.iframe.bundle.js:37937:23)
    at FieldsDndProvider (http://localhost:6006/main.iframe.bundle.js:37960:24)
    at Atlasmap (http://localhost:6006/main.iframe.bundle.js:11935:31)
    at AtlasmapProvider (http://localhost:6006/main.iframe.bundle.js:12472:43)
    at div
    at unboundStoryFn (http://localhost:6006/vendors~main.iframe.bundle.js:53813:30`

**Comment by pleacu** [comment]
@igarashitm - I made the mapping details pane a little easier to read - wdyt?

![ok1](https://user-images.githubusercontent.com/2981421/121191747-410d9680-c83a-11eb-8f7d-ef1c2897088f.png)

**Comment by jpav** [comment]
@pleacu I think the gray that you used is a bit of a problem, especially wrt the blank white rectangle left above Targets. Maybe you could reverse that use and have the Sources and Targets title boxes remain white and the contents in gray?

**Comment by pleacu** [comment]
The way it is now - the Sources and Targets boxes have a gray background (not just the title) with the contents white (it's a little hard to see with the screen capture).  Turning the Sources and Targets boxes white with the contents gray would lose the distinction between SRC/TGT.

**Comment by igarashitm** [comment]
LGTM :+1:

**Comment by igarashitm** [comment]
Ah right, the white space between Sources and Targets looks a bit too wide, having the fact that the vertical space is more expensive.

**Comment by pleacu** [comment]
Hey @igarashitm + @jpav - here's the best I've got.  We can play around after this if anyone desires.

![ok1](https://user-images.githubusercontent.com/2981421/121230533-5ba53700-c85d-11eb-815c-e768f9a397e1.png)

![ok2](https://user-images.githubusercontent.com/2981421/121230572-65c73580-c85d-11eb-8b0e-addece186133.png)
