### ISSUE TITLE
Transformations with "ANY_DATE" aren't working 

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#381]
```
Caused by: io.atlasmap.api.AtlasException: java.lang.IllegalArgumentException: Unsupported field type 'ANY_DATE': corresponding Java class needs to be added in DefaultAtlasConversionService
	at io.atlasmap.java.core.DocumentJavaFieldWriter.write(DocumentJavaFieldWriter.java:139)
	at io.atlasmap.java.module.JavaModule.processTargetFieldMapping(JavaModule.java:194)
	at io.atlasmap.core.DefaultAtlasContext.processTargetFieldMappings(DefaultAtlasContext.java:420)
	at io.atlasmap.core.DefaultAtlasContext.process(DefaultAtlasContext.java:272)
```

**Comment by igarashitm** [comment]
Hi @mmelko , how did you hit this? did AtlasMap UI use `ANY_DATE` as a field type?

`ANY_DATE` is kinda wildcard to capture all the DATE/TIME related field types **by runtime internally**, and it **should not be used** for the actual field type in the inspection result. So if Java inspection is returning `ANY_DATE` for some fields, it's a bug in the inspection.

**Comment by igarashitm** [comment]
@jpav - FYI

**Comment by igarashitm** [comment]
Hmm so `DATE_TIME` is used for field type, which is absolutely correct. `ANY_DATE` support seems to be somehow broken internally...
