### ISSUE TITLE
[BUG] Reset is broken.

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#4016]
Attempting to 
`Reset all mappings and clear all imported documents`
will cause the backend service to NPE:
<pre>
Caused by: java.lang.NullPointerException: null
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:149) ~[na:na]
	at io.atlasmap.json.service.JsonService.performDocumentInspection(JsonService.java:151) ~[atlas-json-service-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at io.atlasmap.service.DocumentService.getDocumentInspectionResultRequest(DocumentService.java:130) ~[atlas-service-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
</pre>
The backend service `getDocumentInspectionResultRequest` should protect itself against a null spec value.  In addition, the UI document service is using the backend service to fetch the active document catalog.  The UI `reset` command should invoke the backend to clear all documents from that catalog.

**Comment by pleacu** [comment]
To reproduce - just load `mockdoc.adm` and `reset`.
