### ISSUE TITLE
Cannot execute AtlasSession created by the other AtlasContext

### ISSUE THREAD

**Issue by lburgazzoli** [atlasmap/atlasmap#867]
After an integration was running on syndesis for a while I saw this exception happening:

```
io.atlasmap.api.AtlasException: Cannot execute AtlasSession created by the other AtlasContext
  at io.atlasmap.core.DefaultAtlasContext.process(DefaultAtlasContext.java:422) ~[io.atlasmap.atlas-core-1.39.5.jar:1.39.5]
  at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:247) ~[io.atlasmap.camel-atlasmap-1.39.5.jar:?]
  at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71) ~[org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79) [io.syndesis.integration.integration-runtime-1.6-SNAPSHOT.jar:1.6-SNAPSHOT]
  at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [org.apache.camel.camel-core-2.23.1.jar:2.23.1]
  at org.apache.camel.component.netty4.handlers.ServerChannelHandler.processAsynchronously(ServerChannelHandler.java:141) [org.apache.camel.camel-netty4-2.23.1.jar:2.23.1]
  at org.apache.camel.component.netty4.handlers.ServerChannelHandler.channelRead0(ServerChannelHandler.java:112) [org.apache.camel.camel-netty4-2.23.1.jar:2.23.1]
  at org.apache.camel.component.netty4.http.handlers.HttpServerChannelHandler.channelRead0(HttpServerChannelHandler.java:195) [org.apache.camel.camel-netty4-http-2.23.1.jar:2.23.1]
  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [io.netty.netty-all-4.1.31.Final.jar:4.1.31.Final]
  at org.apache.camel.component.knative.http.KnativeHttpComponent$Handler.channelRead0(KnativeHttpComponent.java:157) [org.apache.camel.k.camel-knative-http-0.3.2-summit.jar:0.3.2-summit]
  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [io.netty.netty-all-4.1.31.Final.jar:4.1.31.Final]
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty.netty-all-4.1.31.Final.jar:4.1.31.Final]
  at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38) [io.netty.netty-all-4.1.31.Final.jar:4.1.31.Final]
  at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353) [io.netty.netty-all-4.1.31.Final.jar:4.1.31.Final]
  at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) [io.netty.netty-all-4.1.31.Final.jar:4.1.31.Final]
  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [io.netty.netty-all-4.1.31.Final.jar:4.1.31.Final]
  at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by igarashitm** [comment]
So it's here, should never happen. Possibly the AtlasContext is unexpectedly recreated while an AtlasSession is processing.
https://github.com/atlasmap/atlasmap/blob/3ed004b0b8f1397b7cf5f3e07deeded167317cc6/lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java#L415-L417
