### ISSUE TITLE
Convert Volume Unit transformation fails in AtlasService

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#892]
![bug2](https://user-images.githubusercontent.com/2981421/56826060-2a0db500-6829-11e9-938b-8f226501f283.png)

`javax.ws.rs.WebApplicationException: HTTP 400 Bad Request
	at io.atlasmap.service.AtlasService.fromJson(AtlasService.java:749) ~[atlas-service-1.40.0-SNAPSHOT.jar:1.40.0-SNAPSHOT]
	at io.atlasmap.service.AtlasService.createMappingRequest(AtlasService.java:353) ~[atlas-service-1.40.0-SNAPSHOT.jar:1.40.0-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor152.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140) ~[resteasy-jaxrs-3.6.1.Final.jar:3.6.1.Final]
`

**Comment by igarashitm** [comment]
Seems unit enum contract is broken between UI and backend
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type io.atlasmap.v2.VolumeUnitType from String "Cubic Meter": value not one of declared Enum instance names: [CUBIC_FOOT, LITER, GALLON_US_FLUID, CUBIC_METER]
 at [Source: N/A; line: -1, column: -1] (through reference chain: io.atlasmap.v2.AtlasMapping["mappings"]->io.atlasmap.v2.Mappings["mapping"]->java.util.ArrayList[0]->io.atlasmap.v2.Mapping["inputField"]->java.util.ArrayList[0]->io.atlasmap.json.v2.JsonField["actions"]->io.atlasmap.v2.ConvertVolumeUnit["fromUnit"])
```

**Comment by igarashitm** [comment]
OK so it used to be using enum `fromValue()` to deserialize, and it was removed with json deserializer. We need to do same in somewhere else.
https://github.com/atlasmap/atlasmap/pull/877/files#diff-6914bcb8766fd19d1712afb342078389L345

**Comment by igarashitm** [comment]
Actually we had to use name for those enums... maybe change in next version.
