### ISSUE TITLE
[Regression] [Separate] Conversion from 'STRING' to 'DOUBLE' is required but no converter is available 

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#977]
Picking converters doesn't work when using Separate. Source and target are java objects. I've tried with latest master and also atlasmap-1.40.0.fuse-740009.             
![screenshot_20190610_215618](https://user-images.githubusercontent.com/6814482/59222808-a63a3d00-8bca-11e9-931b-8a06eb1a932b.png)

Mapping.json:
```
{
  "AtlasMapping" : {
    "jsonType" : "io.atlasmap.v2.AtlasMapping",
    "dataSource" : [ {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.SourceMappingTestClass",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.SourceMappingTestClass",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.DatesObject",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.DatesObject",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.SourceListsClass",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.SourceListsClass",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.SmallMappingTestClass",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.SmallMappingTestClass",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "sourceArrays",
      "uri" : "atlas:json:sourceArrays",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "sourceJsonArray",
      "uri" : "atlas:json:sourceJsonArray",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "sourceJson",
      "uri" : "atlas:json:sourceJson",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.xml.v2.XmlDataSource",
      "id" : "sourceXmlInstance",
      "uri" : "atlas:xml:sourceXmlInstance",
      "dataSourceType" : "SOURCE",
      "xmlNamespaces" : {
        "xmlNamespace" : [ ]
      }
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "sourceXMLSchema",
      "uri" : "atlas:xml:sourceXMLSchema",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.TargetMappingTestClass",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.TargetMappingTestClass",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.StringObject",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.StringObject",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.TargetListsClass",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.TargetListsClass",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "targetArrays",
      "uri" : "atlas:json:targetArrays",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "targetJsonArray",
      "uri" : "atlas:json:targetJsonArray",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "targetJson",
      "uri" : "atlas:json:targetJson",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "targetXMLSchema",
      "uri" : "atlas:xml:targetXMLSchema",
      "dataSourceType" : "TARGET"
    } ],
    "mappings" : {
      "mapping" : [ {
        "jsonType" : "io.atlasmap.v2.Mapping",
        "inputField" : [ {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "actions" : [ {
            "delimiter" : " ",
            "@type" : "Split"
          } ],
          "docId" : "io.atlasmap.qe.test.SourceMappingTestClass",
          "path" : "/sourceString",
          "fieldType" : "STRING",
          "name" : "sourceString"
        } ],
        "outputField" : [ {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "index" : 0,
          "path" : "/targetDouble",
          "fieldType" : "DOUBLE",
          "name" : "targetDouble"
        }, {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "index" : 1,
          "path" : "/targetCombineString",
          "fieldType" : "STRING",
          "name" : "targetCombineString"
        } ],
        "id" : "mapping.398777"
      } ]
    },
    "lookupTables" : {
      "lookupTable" : [ ]
    },
    "constants" : {
      "constant" : [ ]
    },
    "properties" : {
      "property" : [ ]
    },
    "name" : "UI.491830"
  }
}
```

**Comment by mmelko** [comment]
Hi @igarashitm This is happening also during conditional mappings: 
```
Caused by: io.atlasmap.api.AtlasException: Errors: [Conversion from 'STRING' to 'INTEGER' is required but no converter is available: docId='mapping.571462', path='null'], [Conversion from 'SHORT' to 'INTEGER' is required but no converter is available: docId='mapping.571462', path='null'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:262)
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.component.direct.DirectBlockingProducer.process(DirectBlockingProducer.java:53)
	at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:186)
	at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:86)
	at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:541)
	at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:506)
	at org.apache.camel.impl.ProducerCache.doInProducer(ProducerCache.java:369)
	at org.apache.camel.impl.ProducerCache.sendExchange(ProducerCache.java:506)
	at org.apache.camel.impl.ProducerCache.send(ProducerCache.java:229)
	at org.apache.camel.impl.DefaultProducerTemplate.send(DefaultProducerTemplate.java:144)
	at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:161)
	at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:168)
	at io.atlasmap.qe.test.MappingValidator.processMappingInputMap(MappingValidator.java:94)
	at io.atlasmap.qe.test.MappingValidator.processMapping(MappingValidator.java:75)
	at io.atlasmap.qe.test.MappingValidator.verifyMapping(MappingValidator.java:103)
	at io.atlasmap.qe.test.MappingValidator.verifyMapping(MappingValidator.java:145)
	at io.atlasmap.qe.test.atlas.steps.BackendSteps.saveAndVerifyMappingAs(BackendSteps.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:32)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:26)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:37)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:40)
	at cucumber.api.TestStep.executeStep(TestStep.java:102)
	at cucumber.api.TestStep.run(TestStep.java:83)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:99)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:41)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:108)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

```

Mapping:
```
"mappings" : {
      "mapping" : [ {
        "jsonType" : "io.atlasmap.v2.Mapping",
        "inputFieldGroup" : {
          "jsonType" : "io.atlasmap.v2.FieldGroup",
          "actions" : [ {
            "expression" : "if(ISEMPTY(${0}), ${1}, ${2}",
            "@type" : "Expression"
          } ],
          "field" : [ {
            "jsonType" : "io.atlasmap.java.v2.JavaField",
            "docId" : "io.atlasmap.qe.test.SourceMappingTestClass",
            "index" : 0,
            "path" : "/sourceString",
            "fieldType" : "STRING",
            "name" : "sourceString"
          }, {
            "jsonType" : "io.atlasmap.java.v2.JavaField",
            "docId" : "io.atlasmap.qe.test.SourceMappingTestClass",
            "index" : 1,
            "path" : "/sourceInteger",
            "fieldType" : "INTEGER",
            "name" : "sourceInteger"
          }, {
            "jsonType" : "io.atlasmap.java.v2.JavaField",
            "docId" : "io.atlasmap.qe.test.SourceMappingTestClass",
            "index" : 2,
            "path" : "/sourceShort",
            "fieldType" : "SHORT",
            "name" : "sourceShort"
          } ]
        },
        "inputField" : [ ],
        "outputField" : [ {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "path" : "/targetInteger",
          "fieldType" : "INTEGER",
          "name" : "targetInteger"
        } ],
        "id" : "mapping.571462"
      } ]
    },
```

**Comment by mmelko** [comment]
Hi @igarashitm so this isn't still working with mix of types(String -> numbers).  Now I have 
```Caused by: io.atlasmap.api.AtlasException: Errors: [Unexpected exception is thrown while populating target field: Invoking type convertor failed: docId='io.atlasmap.qe.test.TargetMappingTestClass', path='/targetDouble'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:262)
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.component.direct.DirectBlockingProducer.process(DirectBlockingProducer.java:53)
	at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:186)
	at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:86)
	at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:541)
	at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:506)
	at org.apache.camel.impl.ProducerCache.doInProducer(ProducerCache.java:369)
	at org.apache.camel.impl.ProducerCache.sendExchange(ProducerCache.java:506)
	at org.apache.camel.impl.ProducerCache.send(ProducerCache.java:229)
	at org.apache.camel.impl.DefaultProducerTemplate.send(DefaultProducerTemplate.java:144)
	at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:161)
	at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:168)
	at io.atlasmap.qe.test.MappingValidator.processMappingInputMap(MappingValidator.java:94)
	at io.atlasmap.qe.test.MappingValidator.processMapping(MappingValidator.java:76)
	at io.atlasmap.qe.test.MappingValidator.verifyMapping(MappingValidator.java:103)
	at io.atlasmap.qe.test.MappingValidator.verifyMapping(MappingValidator.java:145)
	at io.atlasmap.qe.test.atlas.steps.BackendSteps.saveAndVerifySeparateMappingWithSeparatorAs(BackendSteps.java:265)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:32)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:26)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:37)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:40)
	at cucumber.api.TestStep.executeStep(TestStep.java:102)
	at cucumber.api.TestStep.run(TestStep.java:83)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:99)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:41)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:108)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


```
I believe this is because of moving to Split action instead of using SeparateStrategy.

**Comment by mmelko** [comment]
used mappings: 
```json
 {
  "AtlasMapping" : {
    "jsonType" : "io.atlasmap.v2.AtlasMapping",
    "dataSource" : [ {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.SourceMappingTestClass",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.SourceMappingTestClass",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.DatesObject",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.DatesObject",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.SourceListsClass",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.SourceListsClass",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.SmallMappingTestClass",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.SmallMappingTestClass",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "sourceArrays",
      "uri" : "atlas:json:sourceArrays",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "sourceJsonArray",
      "uri" : "atlas:json:sourceJsonArray",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "sourceJson",
      "uri" : "atlas:json:sourceJson",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.xml.v2.XmlDataSource",
      "id" : "sourceXmlInstance",
      "uri" : "atlas:xml:sourceXmlInstance",
      "dataSourceType" : "SOURCE",
      "xmlNamespaces" : {
        "xmlNamespace" : [ ]
      }
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "sourceXMLSchema",
      "uri" : "atlas:xml:sourceXMLSchema",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.TargetMappingTestClass",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.TargetMappingTestClass",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.StringObject",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.StringObject",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.TargetListsClass",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.TargetListsClass",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "targetArrays",
      "uri" : "atlas:json:targetArrays",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "targetJsonArray",
      "uri" : "atlas:json:targetJsonArray",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "targetJson",
      "uri" : "atlas:json:targetJson",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "targetXMLSchema",
      "uri" : "atlas:xml:targetXMLSchema",
      "dataSourceType" : "TARGET"
    } ],
    "mappings" : {
      "mapping" : [ {
        "jsonType" : "io.atlasmap.v2.Mapping",
        "inputField" : [ {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "actions" : [ {
            "delimiter" : " ",
            "@type" : "Split"
          } ],
          "docId" : "io.atlasmap.qe.test.SourceMappingTestClass",
          "path" : "/sourceCombineString",
          "fieldType" : "STRING",
          "name" : "sourceCombineString"
        } ],
        "outputField" : [ {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "index" : 0,
          "path" : "/targetDouble",
          "fieldType" : "DOUBLE",
          "name" : "targetDouble"
        }, {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "index" : 1,
          "path" : "/targetShort",
          "fieldType" : "SHORT",
          "name" : "targetShort"
        }, {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "index" : 2,
          "path" : "/targetLong",
          "fieldType" : "LONG",
          "name" : "targetLong"
        }, {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "index" : 3,
          "path" : "/targetFloat",
          "fieldType" : "FLOAT",
          "name" : "targetFloat"
        }, {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "index" : 4,
          "path" : "/targetInteger",
          "fieldType" : "INTEGER",
          "name" : "targetInteger"
        }, {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "index" : 5,
          "path" : "/targetChar",
          "fieldType" : "CHAR",
          "name" : "targetChar"
        }, {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "index" : 6,
          "path" : "/targetString",
          "fieldType" : "STRING",
          "name" : "targetString"
        } ],
        "id" : "mapping.24206"
      } ]
    },
    "lookupTables" : {
      "lookupTable" : [ ]
    },
    "constants" : {
      "constant" : [ ]
    },
    "properties" : {
      "property" : [ ]
    },
    "name" : "UI.480887"
  }
}%  
```

**Comment by igarashitm** [comment]
FYI, now we have an IT testing Split(STRING) => INTEGER
https://github.com/atlasmap/atlasmap/blob/master/lib/itests/core/src/test/java/io/atlasmap/itests/core/MultiplicityTransformationTest.java#L59
https://github.com/atlasmap/atlasmap/blob/master/lib/itests/core/src/test/resources/mappings/atlasmapping-multiplicity-transformation-concatenate-split.json#L126

not sure if it's other field types specific or not, but it looks like a different issue

**Comment by mmelko** [comment]
I believe problem is when more types is involved .. such as String => Integer,String, float etc. It looks like Split expect the collection of the same type.

**Comment by igarashitm** [comment]
OK so mixing different field types at target side. Although it's still expected to work, I would say it's an edge case and not p0.

**Comment by igarashitm** [comment]
So can you file a separate issue, having different field types at target side of split case?

**Comment by mmelko** [comment]
sure here it is: https://github.com/atlasmap/atlasmap/issues/998
