### ISSUE TITLE
[Regression][Separate/Split] Invoking type convertor failed when multiple types of targets

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#998]
When we have mapping such as String -> (Integer, Long etc.. ) following exception is thrown 
```
Caused by: io.atlasmap.api.AtlasException: Errors: [Unexpected exception is thrown while populating target field: Invoking type convertor failed: docId='io.atlasmap.qe.test.TargetMappingTestClass', path='/targetDouble'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:262)
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.component.direct.DirectBlockingProducer.process(DirectBlockingProducer.java:53)
	at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:186)
	at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:86)
	at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:541)
	at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:506)
	at org.apache.camel.impl.ProducerCache.doInProducer(ProducerCache.java:369)
	at org.apache.camel.impl.ProducerCache.sendExchange(ProducerCache.java:506)
	at org.apache.camel.impl.ProducerCache.send(ProducerCache.java:229)
	at org.apache.camel.impl.DefaultProducerTemplate.send(DefaultProducerTemplate.java:144)
	at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:161)
	at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:168)
	at io.atlasmap.qe.test.MappingValidator.processMappingInputMap(MappingValidator.java:94)
	at io.atlasmap.qe.test.MappingValidator.processMapping(MappingValidator.java:76)
	at io.atlasmap.qe.test.MappingValidator.verifyMapping(MappingValidator.java:103)
	at io.atlasmap.qe.test.MappingValidator.verifyMapping(MappingValidator.java:145)
	at io.atlasmap.qe.test.atlas.steps.BackendSteps.saveAndVerifySeparateMappingWithSeparatorAs(BackendSteps.java:265)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:32)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:26)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:37)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:40)
	at cucumber.api.TestStep.executeStep(TestStep.java:102)
	at cucumber.api.TestStep.run(TestStep.java:83)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:99)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:41)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:108)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

used mapping:
```json
 {
  "AtlasMapping" : {
    "jsonType" : "io.atlasmap.v2.AtlasMapping",
    "dataSource" : [ {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.SourceMappingTestClass",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.SourceMappingTestClass",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.DatesObject",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.DatesObject",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.SourceListsClass",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.SourceListsClass",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.SmallMappingTestClass",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.SmallMappingTestClass",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "sourceArrays",
      "uri" : "atlas:json:sourceArrays",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "sourceJsonArray",
      "uri" : "atlas:json:sourceJsonArray",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "sourceJson",
      "uri" : "atlas:json:sourceJson",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.xml.v2.XmlDataSource",
      "id" : "sourceXmlInstance",
      "uri" : "atlas:xml:sourceXmlInstance",
      "dataSourceType" : "SOURCE",
      "xmlNamespaces" : {
        "xmlNamespace" : [ ]
      }
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "sourceXMLSchema",
      "uri" : "atlas:xml:sourceXMLSchema",
      "dataSourceType" : "SOURCE"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.TargetMappingTestClass",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.TargetMappingTestClass",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.StringObject",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.StringObject",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "io.atlasmap.qe.test.TargetListsClass",
      "uri" : "atlas:java?className=io.atlasmap.qe.test.TargetListsClass",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "targetArrays",
      "uri" : "atlas:json:targetArrays",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "targetJsonArray",
      "uri" : "atlas:json:targetJsonArray",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.json.v2.JsonDataSource",
      "id" : "targetJson",
      "uri" : "atlas:json:targetJson",
      "dataSourceType" : "TARGET"
    }, {
      "jsonType" : "io.atlasmap.v2.DataSource",
      "id" : "targetXMLSchema",
      "uri" : "atlas:xml:targetXMLSchema",
      "dataSourceType" : "TARGET"
    } ],
    "mappings" : {
      "mapping" : [ {
        "jsonType" : "io.atlasmap.v2.Mapping",
        "inputField" : [ {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "actions" : [ {
            "delimiter" : " ",
            "@type" : "Split"
          } ],
          "docId" : "io.atlasmap.qe.test.SourceMappingTestClass",
          "path" : "/sourceCombineString",
          "fieldType" : "STRING",
          "name" : "sourceCombineString"
        } ],
        "outputField" : [ {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "index" : 0,
          "path" : "/targetDouble",
          "fieldType" : "DOUBLE",
          "name" : "targetDouble"
        }, {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "index" : 1,
          "path" : "/targetShort",
          "fieldType" : "SHORT",
          "name" : "targetShort"
        }, {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "index" : 2,
          "path" : "/targetLong",
          "fieldType" : "LONG",
          "name" : "targetLong"
        }, {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "index" : 3,
          "path" : "/targetFloat",
          "fieldType" : "FLOAT",
          "name" : "targetFloat"
        }, {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "index" : 4,
          "path" : "/targetInteger",
          "fieldType" : "INTEGER",
          "name" : "targetInteger"
        }, {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "index" : 5,
          "path" : "/targetChar",
          "fieldType" : "CHAR",
          "name" : "targetChar"
        }, {
          "jsonType" : "io.atlasmap.java.v2.JavaField",
          "docId" : "io.atlasmap.qe.test.TargetMappingTestClass",
          "index" : 6,
          "path" : "/targetString",
          "fieldType" : "STRING",
          "name" : "targetString"
        } ],
        "id" : "mapping.24206"
      } ]
    },
    "lookupTables" : {
      "lookupTable" : [ ]
    },
    "constants" : {
      "constant" : [ ]
    },
    "properties" : {
      "property" : [ ]
    },
    "name" : "UI.480887"
  }
}%  
```

**Comment by igarashitm** [comment]
It turned out this case is well documented and is working fine with deprecated SEPARATE mode. Bumping up to p0

**Comment by igarashitm** [comment]
Verified it works for the basic usecase as documented
https://github.com/atlasmap/atlasmap/pull/1010/files#diff-c961b2b1593bb88ef72ee3834f2180abR97

**Comment by igarashitm** [comment]
Also added split(STRING) => [DOUBLE, STRING], works fine.

**Comment by mmelko** [comment]
After some changes in testsuite this works as expected now. Howewer It looks i have problem with some delimiters. I will create new issue for that after investigation. Closing for now.
